/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.*;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;

/**
 *
 * @author zendy
 */
public class BukuView extends javax.swing.JFrame implements buttonInterface{

    /**
     * Creates new form BukuView
     */
    public BukuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListBuku = new javax.swing.JList<>();
        buttonTambah = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        labelStok = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelIsbn = new javax.swing.JLabel();
        labelJudulBuku = new javax.swing.JLabel();
        labelPenulis = new javax.swing.JLabel();
        labelPenerbit = new javax.swing.JLabel();
        labelTahunTerbit = new javax.swing.JLabel();
        labelHarga = new javax.swing.JLabel();
        buttonKembali = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jListBuku.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jListBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListBuku);

        buttonTambah.setBackground(new java.awt.Color(255, 255, 255));
        buttonTambah.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        buttonTambah.setText("Tambah");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        buttonEdit.setBackground(new java.awt.Color(255, 255, 255));
        buttonEdit.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        buttonEdit.setText("Edit");

        buttonHapus.setBackground(new java.awt.Color(255, 255, 255));
        buttonHapus.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        buttonHapus.setText("Hapus");

        labelStok.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        labelStok.setText("Stok                      :");

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jLabel1.setText("List Buku (Klik untuk menampilkan info)");

        labelIsbn.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        labelIsbn.setText("ISBN                      :");

        labelJudulBuku.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        labelJudulBuku.setText("Judul Buku          :    ");

        labelPenulis.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        labelPenulis.setText("Penulis                 :");

        labelPenerbit.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        labelPenerbit.setText("Penerbit                :");

        labelTahunTerbit.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        labelTahunTerbit.setText("Tahun Terbit        :");

        labelHarga.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        labelHarga.setText("Harga                   : ");

        buttonKembali.setBackground(new java.awt.Color(255, 255, 255));
        buttonKembali.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        buttonKembali.setText("Kembali");
        buttonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("INFO BUKU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(buttonTambah)
                        .addGap(12, 12, 12)
                        .addComponent(buttonEdit)
                        .addGap(18, 18, 18)
                        .addComponent(buttonHapus))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelIsbn)
                            .addComponent(labelJudulBuku)
                            .addComponent(labelPenulis)
                            .addComponent(labelPenerbit)
                            .addComponent(labelTahunTerbit)
                            .addComponent(labelHarga)
                            .addComponent(labelStok)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel2)))
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonKembali)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelIsbn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelJudulBuku)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPenulis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPenerbit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTahunTerbit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelHarga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelStok)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEdit)
                    .addComponent(buttonHapus)
                    .addComponent(buttonTambah))
                .addGap(22, 22, 22)
                .addComponent(buttonKembali)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jListBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListBukuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jListBukuMouseClicked

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BukuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BukuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BukuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BukuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BukuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonKembali;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jListBuku;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelHarga;
    private javax.swing.JLabel labelIsbn;
    private javax.swing.JLabel labelJudulBuku;
    private javax.swing.JLabel labelPenerbit;
    private javax.swing.JLabel labelPenulis;
    private javax.swing.JLabel labelStok;
    private javax.swing.JLabel labelTahunTerbit;
    // End of variables declaration//GEN-END:variables


    public JButton getButtonEdit() {
        return buttonEdit;
    }

    public JButton getButtonHapus() {
        return buttonHapus;
    }

    public JButton getButtonTambah() {
        return buttonTambah;
    }
    
    public JButton getButtonKembali(){
        return buttonKembali;
    }

    public JList<String> getjListBuku() {
        return jListBuku;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JLabel getLabelHarga() {
        return labelHarga;
    }

    public JLabel getLabelIsbn() {
        return labelIsbn;
    }

    public JLabel getLabelJudulBuku() {
        return labelJudulBuku;
    }

    public JLabel getLabelPenerbit() {
        return labelPenerbit;
    }

    public JLabel getLabelPenulis() {
        return labelPenulis;
    }

    public JLabel getLabelStok() {
        return labelStok;
    }

    public JLabel getLabelTahunTerbit() {
        return labelTahunTerbit;
    }

    public void setLabel(String ISBN, String judul, String penulis, String penerbit, String tahun, int harga, int stok){
        labelIsbn.setText("ISBN                      :" + ISBN);
        labelJudulBuku.setText("Judul Buku           :" + judul);
        labelPenulis.setText("Penulis                 :" + penulis);
        labelPenerbit.setText("Penerbit                :" + penerbit);
        labelTahunTerbit.setText("Tahun Terbit        :" + tahun);
        labelHarga.setText("Harga                   : " + harga);
        labelStok.setText("Stok                      :" + stok);
    }
    @Override
    public void addListener(ActionListener e) {
        buttonEdit.addActionListener(e);
        buttonHapus.addActionListener(e);
        buttonTambah.addActionListener(e);
        buttonKembali.addActionListener(e);
    }
    public void addMouseClicked(MouseListener e){
        jListBuku.addMouseListener(e);
    }

    public void fillJlist(String[] arr){
        DefaultListModel model = new DefaultListModel();
        for (int i = 0; i < arr.length;i++){
            model.addElement(arr[i]);
        }
        jListBuku.setModel(model);
    }
    public void disableButton(){
        buttonEdit.setEnabled(false);
        buttonHapus.setEnabled(false);
    }
    public void enableButton(){
        buttonEdit.setEnabled(true);
        buttonHapus.setEnabled(true);
    }
    public void hideButton(){
        buttonTambah.setVisible(false);
        buttonHapus.setVisible(false);
        buttonEdit.setVisible(false);
    }
}
